# Load Data

## Import Library

In [1]:
import os
import glob
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

## Menentukan lokasi dataset

In [2]:
dataset_path = "../Datasheet/OBD-Anomaly-Detection/dataset"

print(dataset_path)

../Datasheet/OBD-Anomaly-Detection/dataset

## Melihat seluruh file csv

In [3]:
csv_files = glob.glob(os.path.join(dataset_path, "*.csv"))

print("Jumlah File :", len(csv_files))

for file in csv_files:
    print(os.path.basename(file))

Jumlah File : 18
1.csv
10_phase_2_uet-Haier-PC.csv
10_phase_2_uet.csv
ABCEdit.csv
cloudobd-mobilehub-1713608645-ObdData.csv
From_Phase2_To_UET_Speed.csv
From_UET_To_Phase2_Speed.csv
MafDData.csv
OBD Reading.csv
OBD Readings MAF.csv
obd-mobilehub-1549951896-ObdData (1).csv
obd-mobilehub-1549951896-ObdData.csv
PhaseII_2_uet_speed.csv
PhaseII_2_uet_Time.csv
separated data.csv
UET_2_Phase2.csv
UET_2_Phase2_Speed.csv
UET_2_Phase2_Time.csv

## Membaca seluruh dataset

In [4]:
all_data = []

for file in csv_files:

    try:
        df = pd.read_csv(file)

        df["source_file"] = os.path.basename(file)

        all_data.append(df)

        print(os.path.basename(file),
              " --> ",
              df.shape)

    except Exception as e:

        print(file)
        print(e)

1.csv  -->  (19, 4)
10_phase_2_uet-Haier-PC.csv  -->  (34, 13)
10_phase_2_uet.csv  -->  (34, 4)
ABCEdit.csv  -->  (44, 17)
cloudobd-mobilehub-1713608645-ObdData.csv  -->  (94, 8)
From_Phase2_To_UET_Speed.csv  -->  (44, 9)
From_UET_To_Phase2_Speed.csv  -->  (69, 10)
MafDData.csv  -->  (44, 5)
OBD Reading.csv  -->  (95, 2)
OBD Readings MAF.csv  -->  (45, 2)
obd-mobilehub-1549951896-ObdData (1).csv  -->  (45, 16)
obd-mobilehub-1549951896-ObdData.csv  -->  (95, 8)
PhaseII_2_uet_speed.csv  -->  (44, 15)
PhaseII_2_uet_Time.csv  -->  (34, 4)
separated data.csv  -->  (99, 21)
UET_2_Phase2.csv  -->  (68, 15)
UET_2_Phase2_Speed.csv  -->  (61, 5)
UET_2_Phase2_Time.csv  -->  (62, 5)

## Menggabungkan seluruh dataset

In [5]:
dataset = pd.concat(all_data,
                    ignore_index=True)

print(dataset.shape)

(1030, 49)

## Melihat data

In [6]:
dataset.head()

,lat,lng,name,source_file,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,MAF,DateTime,Speed,GPH,LPH,Unnamed: 12,KPL,Unnamed: 14,CO2 Emissions,timeStamp (N),DateTime (S),altitude (N),latitude (N),longitude (N),readings (M),vehicleId (S),Time,Speed.1,note,name,rpm,name.1,rpm.1,time,speed,894,RPM,speed.1,time.1,speed.2,Unnamed: 15,Speed (km/h),Engine RPM,Unnamed: 19,name,Unnamed: 13
0,33.997577,71.491204,6:44:00 PM,1.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,33.997541,71.490413,6:44:00 PM,1.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,33.997589,71.489618,6:44:00 PM,1.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,33.997596,71.489163,6:45:00 PM,1.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,33.997798,71.483814,6:45:00 PM,1.csv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Informasi dataset

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 49 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   lat            601 non-null    float64
 1   lng            601 non-null    float64
 2   name           243 non-null    object
 3   source_file    1030 non-null   object
 4   Unnamed: 3     0 non-null      float64
 5   Unnamed: 4     0 non-null      float64
 6   Unnamed: 5     34 non-null     float64
 7   Unnamed: 6     95 non-null     object
 8   Unnamed: 7     95 non-null     float64
 9   Unnamed: 8     95 non-null     float64
 10  Unnamed: 9     0 non-null      float64
 11  Unnamed: 10    0 non-null      float64
 12  Unnamed: 11    0 non-null      float64
 13  MAF            88 non-null     float64
 14  DateTime       88 non-null     object
 15  Speed          201 non-null    float64
 16  GPH            44 non-null     float64
 17  LPH            44 non-null     float64
 18  Unnamed: 12    2 non-null      object
 19  KPL            44 non-null     float64
 20  Unnamed: 14    34 non-null     float64
 21  CO2 Emissions  44 non-null     float64
 22  timeStamp (N)  234 non-null    float64
 23  DateTime (S)   234 non-null    object
 24  altitude (N)   234 non-null    float64
 25  latitude (N)   295 non-null    float64
 26  longitude (N)  329 non-null    object
 27  readings (M)   374 non-null    object
 28  vehicleId (S)  234 non-null    object
 29  Time           219 non-null    object
 30  Speed.1        113 non-null    float64
 31  note           279 non-null    object
 32   name          44 non-null     object
 33  rpm            139 non-null    object
 34   name.1        44 non-null     object
 35  rpm.1          33 non-null     float64
 36  time           95 non-null     object
 37  speed          95 non-null     float64
 38  894            94 non-null     float64
 39  RPM            94 non-null     object
 40  speed.1        61 non-null     float64
 41  time.1         62 non-null     object
 42  speed.2        61 non-null     float64
 43  Unnamed: 15    34 non-null     float64
 44  Speed (km/h)   62 non-null     float64
 45  Engine RPM     62 non-null     float64
 46  Unnamed: 19    1 non-null      float64
 47  name           68 non-null     object
 48  Unnamed: 13    1 non-null      object
dtypes: float64(30), object(19)
memory usage: 394.4+ KB

## Statistik dataset

In [8]:
dataset.describe()

,lat,lng,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,MAF,Speed,GPH,LPH,KPL,Unnamed: 14,CO2 Emissions,timeStamp (N),altitude (N),latitude (N),Speed.1,rpm.1,speed,894,speed.1,speed.2,Unnamed: 15,Speed (km/h),Engine RPM,Unnamed: 19
count,601.000000,601.000000,0.0,0.0,34.000000,95.000000,95.000000,0.0,0.0,0.0,88.00000,201.000000,44.000000,44.000000,44.000000,34.000000,44.000000,2.340000e+02,234.000000,295.000000,113.000000,33.000000,95.000000,94.000000,61.000000,61.000000,34.000000,62.000000,62.000000,1.0
mean,33.990944,71.465229,NaN,NaN,26.823529,71.464350,25.052632,NaN,NaN,NaN,6.98250,25.164179,5.620912,21.078422,1.416503,26.823529,1.789560,1.562523e+12,334.035363,33.992437,23.150442,1271.787879,25.052632,1281.893617,24.065574,24.065574,1253.794118,23.677419,1281.016129,989.0
std,0.010454,0.016148,NaN,NaN,19.173009,0.017069,17.366125,NaN,NaN,NaN,5.72966,18.051535,4.639115,17.396682,1.282204,19.173009,1.523132,3.085802e+09,14.643668,0.010075,17.265894,256.137263,17.366125,275.553069,16.356313,16.356313,273.178683,16.507101,289.405410,NaN
min,33.969200,71.442596,NaN,NaN,0.000000,71.442596,0.000000,NaN,NaN,NaN,1.84000,0.000000,1.481200,5.554500,0.000000,0.000000,0.000000,1.560000e+12,311.000000,33.969200,0.000000,767.000000,0.000000,757.000000,0.000000,0.000000,660.000000,0.000000,757.000000,989.0
25%,33.981843,71.448531,NaN,NaN,12.000000,71.448086,10.000000,NaN,NaN,NaN,3.48250,10.000000,2.803412,10.512797,0.561549,12.000000,0.683358,1.560000e+12,323.574371,33.985137,6.000000,1127.000000,10.000000,1147.750000,9.000000,9.000000,1118.000000,8.250000,1148.000000,989.0
50%,33.997079,71.464226,NaN,NaN,23.000000,71.458425,25.000000,NaN,NaN,NaN,3.58000,23.000000,2.881900,10.807125,1.035469,23.000000,1.495871,1.560000e+12,329.383911,33.997574,20.000000,1263.000000,25.000000,1258.000000,26.000000,26.000000,1258.500000,25.000000,1254.500000,989.0
75%,33.998084,71.483349,NaN,NaN,43.000000,71.485107,39.500000,NaN,NaN,NaN,11.59750,42.000000,9.335987,35.009953,2.011239,43.000000,2.393642,1.566280e+12,342.719788,33.998261,37.000000,1443.000000,39.500000,1476.250000,37.000000,37.000000,1433.500000,37.000000,1480.250000,989.0
max,34.002927,71.491421,NaN,NaN,60.000000,71.491421,60.000000,NaN,NaN,NaN,22.42000,63.000000,18.048100,67.680375,4.876927,60.000000,6.196739,1.566290e+12,376.970154,34.002927,60.000000,2023.000000,60.000000,2023.000000,57.000000,57.000000,2023.000000,57.000000,1992.000000,989.0

## Missing Value

In [9]:
dataset.isnull().sum()

lat               429
lng               429
name              787
source_file         0
Unnamed: 3       1030
Unnamed: 4       1030
Unnamed: 5        996
Unnamed: 6        935
Unnamed: 7        935
Unnamed: 8        935
Unnamed: 9       1030
Unnamed: 10      1030
Unnamed: 11      1030
MAF               942
DateTime          942
Speed             829
GPH               986
LPH               986
Unnamed: 12      1028
KPL               986
Unnamed: 14       996
CO2 Emissions     986
timeStamp (N)     796
DateTime (S)      796
altitude (N)      796
latitude (N)      735
longitude (N)     701
readings (M)      656
vehicleId (S)     796
Time              811
Speed.1           917
note              751
 name             986
rpm               891
 name.1           986
rpm.1             997
time              935
speed             935
894               936
RPM               936
speed.1           969
time.1            968
speed.2           969
Unnamed: 15       996
Speed (km/h)      968
Engine RPM        968
Unnamed: 19      1029
name              962
Unnamed: 13      1029
dtype: int64

## Menyimpan dataset gabungan

In [10]:
dataset.to_csv("../Datasheet/OBD-Anomaly-Detection/dataset/all_dataset.csv",
               index=False)

print("Dataset berhasil disimpan.")

Dataset berhasil disimpan.

Notebook ini berfungsi sebagai fondasi. Setelah all_dataset.csv berhasil dibuat, notebook 02_Preprocessing.ipynb akan menggunakan file tersebut untuk melakukan pembersihan data, normalisasi, pembuatan label anomali, dan menyiapkan data yang siap digunakan oleh model Isolation Forest dan Random Forest.